---
- hosts: 'host*'
  tasks:
  - name: Setup key for docker
    apt_key: keyserver=ha.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
    become: yes

  - name: Add docker engine repo
    apt_repository: repo='deb [arch=amd64] https://apt.dockerproject.org/repo ubuntu-xenial experimental' update_cache=yes
    become: yes

  - name: Add docker
    apt: name=docker-engine state=present
    become: yes

  - name: Add user vagrant to docker group to allow non-sudo access
    user: name=vagrant append=yes groups=docker
    become: yes

  - name: Verify installed docker is right version
    command: curl --unix-socket /var/run/docker.sock http:/info
    register: docker_version

  - assert: { that: "(docker_version.stdout|from_json)['ExperimentalBuild'] == true" }

  - assert: { that: "(docker_version.stdout|from_json)['ServerVersion']|match('1.12') == true" }

  - name: Enable default arp_notify sysctl
    sysctl: name=net.ipv4.conf.all.arp_notify value=1 sysctl_file=/etc/sysctl.d/docker.conf reload=yes
    become: yes

  - name: Enable all arp_notify sysctl
    sysctl: name=net.ipv4.conf.default.arp_notify value=1 sysctl_file=/etc/sysctl.d/docker.conf reload=yes
    become: yes

  - name: Enable arp_notify for every interface
    sysctl: name=net.ipv4.conf.{{ item }}.arp_notify value=1 sysctl_file=/etc/sysctl.d/docker.conf reload=yes
    with_items: "{{ ansible_interfaces }}"
    ignore_errors: yes
    become: yes
